import React from 'react';

import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';

import { albumArchives, getPosts, PostInterface } from '../lib/posts';
import { Masthead, PostIndex, Subhead } from '../components';

export const getStaticProps: GetStaticProps = async (context) => {
  const allAlbums = albumArchives.map(archive => getPosts(archive)).flat();

  return {
    props: {
      posts: allAlbums,
    }
  }
}

interface AllAlbumsInterface {
  posts: PostInterface[];
}

const Home: NextPage<AllAlbumsInterface> = ({ posts }) => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Masthead title="Taylor Smith">
          <Subhead>A simple photo blog.</Subhead>
        </Masthead>
        {posts?.length && (<PostIndex posts={posts} />) }
      </main>
    </div>
  );
}

export default Home;
